version: "3"

tasks:
  install:
    run: once
    desc: Install node modules
    sources:
      - package.json
      - pnpm-lock.yaml
    generates:
      - node_modules/**/*
    cmds:
      - pnpm install

  clean:
    desc: Remove node modules
    cmds:
      - task: clean-build
      - rm -rf node_modules
      - rm -rf .task

  clean-build:
    cmds:
      - rm -rf out
      - rm -rf *.vsix

  test:
    desc: Run tests
    deps: [install]
    cmds:
      - pnpm run test

  lint:
    desc: Run linter checks
    deps: [install]
    cmds:
      - pnpm run lint

  bundle:
    desc: Bundle the extension into a single JS file
    deps: [clean-build, install]
    sources:
      - src/**/*
      - package.json
    generates:
      - out/extension.js
    cmds:
      - pnpm run bundle

  package:
    desc: Package extension into a .vsix file
    deps: [clean-build, install]
    sources:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - res/**/*
    generates:
      - out/extension.js
      - "*.vsix"
    cmds:
      - pnpm run package
