name: Test
on:
  pull_request:
  push:
    tags:
      - v*
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5

      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24.x
          # cache: "pnpm"

      # This is disabled until https://github.com/microsoft/vscode-test-cli/issues/77
      # is resolved. We don't have any tests anyway.
      # - run: pnpm install
      # - run: xvfb-run -a pnpm test
      #   if: runner.os == 'Linux'
      # - run: pnpm test
      #   if: runner.os != 'Linux'
